# Site Settings
name: NJH Blog
title: NJH Blog
description: NJHDev © 2021 * Powered by NJHDev *
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: 🏠Home
    url: /
  - title: 🤹‍♂️About
    url: /about
  - title: 📞Contact
    url: /contact
  - title: 📌Tags
    url: /tags
  - title: 📝Release notes
    url: /release
footermenu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
email: mark0112@naver.com
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xwkaqwwz


# Social Media Settings
# Remove the item if you don't need it
github_username: njhdev
facebook_username: penguin0112
twitter_username:
instagram_username: 0112_njh
instagram2_username: njh_pnf
youtube_channel_id: UCaRLVOdlax5fYa_2Z18QRXQ
linkedin_username:
medium_username:


# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://njhdev.com" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_post_btn: true
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content
  - jekyll-sitemap
  - jekyll-feed

# Exclude my node related stuff
exclude: [
  'package.json',
  'package-lock.json',
  'src',
  'node_modules',
  'initpost.sh',
  'Gemfile',
  'Gemfile.lock',
  'gulpfile.js',
  'README.md',
  'admin'
  'googledd225d9d59309ea3.html',
  'naver759c7acd1e7f25d5f3a5c1d72aef2301.html'
]

category: [
  'flute',
  'midi',
  'blog'
]

# Theme
version: 
